Traceback (most recent call last):
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/main.py", line 44, in <module>
    runner.run()
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/runner.py", line 70, in run
    self.trainer.train(train_dataloader, val_dataloader)
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/trainer.py", line 69, in train
    outputs = self.model(batch)
  File "/Users/jinchai/MQ/Experiment/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jinchai/MQ/Experiment/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/models/BERT4Rec/_model.py", line 163, in forward
    masked_item_seqs, masked_labels = self.mask_tokens(item_seqs.clone())
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/models/BERT4Rec/_model.py", line 113, in mask_tokens
    probability_matrix.masked_fill_(padding_mask, value=0.0)
RuntimeError: expected self and mask to be on the same device, but got mask on mps:0 and self on cpu
Traceback (most recent call last):
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/main.py", line 44, in <module>
    runner.run()
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/runner.py", line 70, in run
    self.trainer.train(train_dataloader, val_dataloader)
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/trainer.py", line 69, in train
    outputs = self.model(batch)
  File "/Users/jinchai/MQ/Experiment/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jinchai/MQ/Experiment/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/models/BERT4Rec/_model.py", line 163, in forward
    masked_item_seqs, masked_labels = self.mask_tokens(item_seqs.clone())
  File "/Users/jinchai/MQ/Experiment/6服务器实验/TAGDiff/models/BERT4Rec/_model.py", line 113, in mask_tokens
    probability_matrix.masked_fill_(padding_mask, value=0.0)
RuntimeError: expected self and mask to be on the same device, but got mask on mps:0 and self on cpu
